name: Build snapshot of PR

on: pull_request

env:
  REGISTRY_IMAGE: ghcr.io/306bobby-projects/boab-music-bot

jobs:
  build:
    name: Build snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          echo "PLATFORM_PAIR=linux-amd64" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: type=ref,event=pr

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time

      - name: Build
        id: build
        uses: docker/build-push-action@v6
        with:
          outputs: type=docker,dest=/tmp/image-${{ env.PLATFORM_PAIR }}.tar
          platforms: linux/amd64
          tags: |
            ${{ env.REGISTRY_IMAGE }}:${{ github.sha }}-${{ env.PLATFORM_PAIR }}
          build-args: |
            COMMIT_HASH=${{ github.sha }}
            BUILD_DATE=${{ steps.current-time.outputs.time }}

      - name: Export Docker meta output
        shell: bash
        run: echo $DOCKER_METADATA_OUTPUT_JSON > /tmp/metadata.json

      - name: Upload metadata
        uses: actions/upload-artifact@v4
        with:
          name: metadata
          path: /tmp/metadata.json
          overwrite: true

      - name: Export SHA
        run: |
          echo "${{ github.sha }}" > /tmp/sha.txt

      - name: Upload SHA
        uses: actions/upload-artifact@v4
        with:
          name: sha
          path: /tmp/sha.txt
          overwrite: true

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: image-${{ env.PLATFORM_PAIR }}
          path: /tmp/image-${{ env.PLATFORM_PAIR }}.tar
          if-no-files-found: error
          retention-days: 1

      - name: Save PR number in artifact
        shell: bash
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: echo $PR_NUMBER > /tmp/pull_request_number.txt
      - name: Upload PR number
        uses: actions/upload-artifact@v4
        with:
          name: pull_request_number
          path: /tmp/pull_request_number.txt
          overwrite: true
